Exam/dotnet/backend/Models/ErrorViewModel.cs
namespace backend.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Exam/dotnet/backend/Controllers/CrudController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using backend.Models;

namespace backend.Controllers;

public class CrudController : Controller
{
    private readonly ILogger<CrudController> _logger;

    public CrudController(ILogger<CrudController> logger)
    {
        _logger = logger;
    }
   

    public static Boolean flag=false;
    public static List<User> temp;
    public IActionResult Display()
    {
        if(flag==false){
             List<User> users=Logic.GetUser();
             ViewData["display"]=users;
        }else{
            ViewData["display"]=temp;
            flag=false;
        }
       
        return View();
    }

       public IActionResult insert()
    {   
        return View();
    }

     

    public IActionResult insert2(String name,String email)
    {
        // Console.WriteLine("------------------------------------");
        //             Console.WriteLine("------------------------------------");
        //             Console.WriteLine("------------------------------------");
        //             Console.WriteLine("------------------------------------");
        //             Console.WriteLine(name+" "+email);
            Logic.SendUser(new User(name,email));
            return Redirect("/Home/Index");
    }
  public IActionResult delete()
    {   
        return View();
    }
    public IActionResult delete2(int id)
    {   
        Logic.DeleteUser(id);
        return Redirect("/Home/Index");
    }
      public IActionResult update()
    {   
        return View();
    }
      public IActionResult update2(int id,string name,string email)
    {   
        Logic.UpdateUser(new User(id,name,email));
        return Redirect("/Home/Index");
    }
        public IActionResult getbyname()
    {   
        return View();
    }
         public IActionResult getbyname2(String name)
    {   
        
        flag=true;
        temp=Logic.GetUserByName(name);
        return Redirect("/crud/display");
    }
   
}

Exam/dotnet/backend/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using backend.Models;

namespace backend.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }
   
}

Exam/dotnet/backend/Views/Crud/delete.cshtml
@{
    ViewData["Title"] = "delete";
}


<form action="/crud/delete2">
 <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Please insert your ID</label>
    <input type="text" class="form-control" id="id" name="id" aria-describedby="emailHelp">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

Exam/dotnet/backend/Views/Crud/display.cshtml
@{
    ViewData["Title"] = "Home Page";
    List<User> U=(List<User>)ViewData["display"];
}

<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">email</th>
    </tr>
  </thead>
  <tbody>
    @{
    
        @foreach (User item in U)
        {
                 <tr>
                 <th>@item.Id</th>
                 <td>@item.Name</td>
                 <td>@item.Email</td>
                 </tr>
            
        }
     

    }
    
  </tbody>
</table>

Exam/dotnet/backend/Views/Crud/getbyname.cshtml
@{
    ViewData["Title"] = "getbyname";
}


<form action="/crud/getbyname2">
 <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Please insert name</label>
    <input type="text" class="form-control" id="name" name="name" aria-describedby="emailHelp">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

Exam/dotnet/backend/Views/Crud/insert.cshtml
@{
    ViewData["Title"] = "Insert";
}


<form action="/crud/insert2">
 <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Name</label>
    <input type="text" class="form-control" id="name" name="name" aria-describedby="emailHelp">
  </div>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

Exam/dotnet/backend/Views/Crud/update.cshtml
@{
    ViewData["Title"] = "Update";
}


<form action="/crud/update2">
<div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Enter id </label>
    <input type="number" class="form-control" id="id" name="id" aria-describedby="emailHelp">
  </div>
 <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Name</label>
    <input type="text" class="form-control" id="name" name="name" aria-describedby="emailHelp">
  </div>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

Exam/dotnet/backend/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "index";
}

<div class="text-center">
    <h1 class="display-4">Welcome to </h1> <br>
    <h1>End module</h1>
</div>

Exam/dotnet/backend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - backend</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/backend.styles.css" asp-append-version="true" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" asp-controller="home" asp-action="index">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-controller="Crud" asp-action="display">Display</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-controller="crud" asp-action="insert">Insert</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" asp-controller="crud" asp-action="delete">Delete</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" asp-controller="crud" asp-action="update">Update</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-controller="crud" asp-action="Getbyname">Get by name</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - backend - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>